service: jobcanjs

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs4.3
  iamRoleARN:
  profile:

package:
  artifact: target/package.zip

functions:
  beatjs:
    handler: handler.beat
    timeout: 10
    events:
      - http:
          path: working
          method: post
      - http:
          path: working
          method: delete
